### ISSUE TITLE
not implemented on windows/amd64

### ISSUE THREAD

**Issue by qin-nz** [go-ping/ping#105]
version: `github.com/go-ping/ping v0.0.0-20200918120429-e8ae07c3cec8`

Run following code on Windows 10, it says `not implemented on windows/amd64`.

```
package main

import (
	"fmt"

	"github.com/go-ping/ping"
)

func main() {
	pinger, err := ping.NewPinger("180.76.76.76")
	pinger.SetPrivileged(true)
	pinger.Count = 3
	err = pinger.Run()
	if err != nil {
		fmt.Println(err)
	}
}

```

**Comment by houaq** [comment]
Same problem +1!

**Comment by houaq** [comment]
The error is caused by `SetControlMessage` call, It seems like to check the packet TTL. I solved this by comment it out, not sure about other side effects.

**Comment by c0decave** [comment]
> The error is caused by `SetControlMessage` call, It seems like to check the packet TTL. I solved this by comment it out, not sure about other side effects.
Interesting, at my side the linux version crashes, the windows version still throws the same error message :(

**Comment by CHTJonas** [comment]
I appears this is a limitation in the Go `x/net/ipv{4|6}` packages:

- https://pkg.go.dev/golang.org/x/net/ipv4#pkg-note-BUG
- https://pkg.go.dev/golang.org/x/net/ipv6#pkg-note-BUG

https://github.com/go-ping/ping/blob/671c40f29adc8190ded8c57bbebf9b6ea534c7ea/ping.go#L452-L454

Since we're already checking whether the `ControlMessage` is present or not I think it's safe to simply pass over the `conn.IPv4PacketConn().SetControlMessage(ipv4.FlagTTL, true)` code lines on Windows, ditto IPv6.
