### ISSUE TITLE
Should the `Size` in function `New` be `timeSliceLength+trackerLength` ?

### ISSUE THREAD

**Issue by chenlujjj** [go-ping/ping#124]
In function `sendICMP`:
```
	t := append(timeToBytes(time.Now()), intToBytes(p.Tracker)...)
	if remainSize := p.Size - timeSliceLength - trackerLength; remainSize > 0 {
		t = append(t, bytes.Repeat([]byte{1}, remainSize)...)
	}

	body := &icmp.Echo{
		ID:   p.id,
		Seq:  p.sequence,
		Data: t,
	}
```
so `len(t)=16`, not p.Size which is 8。

When run command: `go run cmd/ping/ping.go -c 5 -i 200ms  www.baidu.com `, output is:
```
PING www.baidu.com (180.101.49.12):
24 bytes from 180.101.49.12: icmp_seq=0 time=10.268ms ttl=51
24 bytes from 180.101.49.12: icmp_seq=1 time=8.643ms ttl=51
24 bytes from 180.101.49.12: icmp_seq=2 time=8.947ms ttl=51
24 bytes from 180.101.49.12: icmp_seq=3 time=9.439ms ttl=51
^C
--- www.baidu.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max/stddev = 8.643ms/9.32425ms/10.268ms/614.461µs
```
Received packet size is 24 bytes, so the sent packet size is 16 bytes.

If I misunderstand something here, please point out. Thanks.

**Comment by PaulChenAU** [comment]
My understanding is yes since ```p.Size``` equals to 8 which is timeSliceLength as shown in the constructor.
```go
if remainSize := p.Size - timeSliceLength - trackerLength; remainSize > 0 {
    t = append(t, bytes.Repeat([]byte{1}, remainSize)...)
}
```
and the code inside this if statement will never get executed in my opinion.   

Actually, you can refer to the ```go-fastping``` repository as it sends ```icmp.Echo``` message and transforms current timestamp to bytes array with length 8 as the data body. So ```go-fastping``` set p.Size = 8 which is timeSliceLength .  
  
However, this ping repo uses the current timestamp as well as the unique tracker int as the data body. Therefore, I think p.Size inside the ```New()``` constructor should add trackerLength.

**Comment by CHTJonas** [comment]
Thanks for this. I agree that the default value we set for `Size` in the `New()` helper method is incorrect, although this shouldn't really have any noticeable effect apart from being wrong. Worth noting that the code inside that block will get executed if someone initialises a `ping.Pinger` manually without using the helper, or if they override the default `p.Size`.
