### ISSUE TITLE
maybe recvICMP func return packet with a slice byte array?

### ISSUE THREAD

**Issue by lstaasRM** [go-ping/ping#69]
do U think "recv <- &packet{bytes: bytes[:n], nbytes: n, ttl: ttl}" replace of "recv <- &packet{bytes: bytes, nbytes: n, ttl: ttl}" will be better?

**Comment by sparrc** [comment]
it might, any reason in particular you'd like to make that change?

**Comment by CHTJonas** [comment]
Arguably these should **always** be the same and we should return an error if `n != len(bytes)`.

**Comment by CHTJonas** [comment]
On second thoughts, no they shouldn't. That method will receive other kinds of ICMP messages not necessarily sent by the Pinger. For example someone could ping an endpoint using the UNIX ping command with a size of 56 and also ping it using our Go Pinger with a size of 1472. We discard the packets from the UNIX ping command because their ID and tracker don't match but we still need to deserialise them correctly so we can pass them to the `(*Pinger).processPacket(*packet)` method.

Also this would be entirely resolved by #138 so I shall close in favour of merging that.
